apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - args:
            - npm
            - run
            - dev
          image: api
          name: api
          ports:
            - containerPort: 3000
            - containerPort: 9229
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app
              name: api-persistentvolume
      volumes:
        - name: api-persistentvolume
          persistentVolumeClaim:
            claimName: api-persistentvolume
