apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-persistentvolume
  labels:
    app: api-persistentvolume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

